@startuml
Frontend -> WriteBucketController: JSON Payload
WriteBucketController -> CommandBus: CreateBucketCommand
CommandBus -> CreateBucketCommandHandler: CreateBucketCommand
CreateBucketCommandHandler -> WriteBucketRepository: Bucket
WriteBucketRepository -> DATABASE: create statement
DATABASE -> WriteBucketRepository
WriteBucketRepository -> CreateBucketCommandHandler
CreateBucketCommandHandler -> CommandBus
CommandBus -> WriteBucketController
CommandBus --> CommandBus: CommandEvent
WriteBucketController -> Frontend: HTTP 201 created
@enduml
