@startuml
FRONTEND -> WriteBucketController: JSON Payload
WriteBucketController -> CommandBus: CreateBucketCommand
CommandBus --> CommandBus: try: creates event
CommandBus -> CreateBucketHandler: CreateBucketCommand
CreateBucketHandler -> WriteBucketRepository: Bucket
WriteBucketRepository -> DATABASE: create statement
CommandBus --> CommandBus: catch: set exception
DATABASE -> WriteBucketRepository
WriteBucketRepository -> CreateBucketHandler
CreateBucketHandler -> CommandBus
CommandBus -> WriteBucketController
CommandBus --> CommandBus: finally: publishes event
WriteBucketController -> FRONTEND: HTTP 201 created
@enduml
